In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
M = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
print(M)
b = np.array([1.,3.,7.])
print(b)
z= np.array([0.,0.,0.])
print(z)

[[ 3. -1. -1.]
 [-1.  3.  1.]
 [ 2.  1.  4.]]
[1. 3. 7.]
[0. 0. 0.]


In [4]:
def GausJordan(A_,b_,ones = False):
    
    A = A_.copy()
    b = b_.copy()
    
    n = A.shape[0]
    
    for i in range(n):
        
        if ones:
            b[i] /= A[i,i]
            A[i,:] /= A[i,i]
           
        
        for j in range(i+1,n):
            
            a = A[j,i]/A[i,i]
            A[j,:] -= a*A[i,:]
            b[j] -= a*b[i]
         
       
    x = np.zeros_like(b)

    
    for i in reversed(range(n)):
        #print(i)
    
        x[i] = b[i]
        
        for j in range( i+1, n ):
            x[i] -= A[i,j]*x[j]
        
        if not ones:
            x[i] /= A[i,i]
    
    return x,A,b

In [5]:
x,A,b_ = GausJordan(M,b)

In [6]:
x

array([1., 1., 1.])

In [19]:
def gauss_seidel(A_, b_,x_):
    A = A_.copy()
    b = b_.copy()
    x= x_.copy()
    n = A.shape[0]
    it = 0
    
    for k in range(n):
        it = it + 1   
        x_viejo  = x.copy()
        
        for i in range(n):
            x[i] = (b[i] - np.dot(A[i,:i], x[:i]) - np.dot(A[i,(i+1):], x_viejo[(i+1):])) / A[i ,i]
    
           
    return x,it

In [20]:
gauss_seidel(M,b,z)

(array([0.96296296, 1.00617284, 1.01697531]), 3)